CROSS_COMPILE=arm-hismall-linux-
CC:=$(CROSS_COMPILE)gcc
CXX:=$(CROSS_COMPILE)g++


SRC = cores_test.c \
      parameter_test.c

OBJ := $(SRC:.c=.o)

INCLUDES = -I../../common \
		   -I../

LIBS=../libcores.a

CFLAGS+=$(INCLUDES)

all:cores_test parameter_test
cores_test:cores_test.o
	$(CC) -o $@ $< $(LIBS)
	@rm -f corest_test.o
parameter_test:parameter_test.o
	$(CC) -o $@ $< $(LIBS)
	@rm -f corest_test.o
%.o:%.c
	$(CC) $(CFLAGS) -Wall  -o $@ -c $<

clean:
	rm -f cores_test
	rm -f parameter_test
	rm -f *.o 


